### ISSUE TITLE
Validate before publish

### ISSUE THREAD

**Issue by WillBeebe** [massdriver-cloud/massdriver-cli#101]
One example of yaml that will crash the frontend if included in an app / bundle and published.

```yaml
ui:
  image:
    repository:
       # ui:field: containerRepositoriesDropdown
       # cloud: aws
```
