### ISSUE TITLE
mass app templates new

### ISSUE THREAD

**Issue by coryodaniel** [massdriver-cloud/massdriver-cli#104]
Add a command for creating new templates quickly.

* [ ] Drop a `massdriver.yaml` file in template form
* [ ] mkdir `src`

```yaml
schema: draft-07
name: <md .Name md>
description: <md .Description md>
ref: github.com/YOUR_ORG/<md .Ref md>
access: private
type: application

params:
  required:
  - port
  - log_level
  properties:
    port:
      title: Port
      description: "The port number to run on. This is an example value, this could be anything!"
      type: string
    log_level:
      type: string
      title: Log Level
      description: "The log level to log at. This is an example value, this could be anything!"
      enum:
        - error
        - warning
        - info

connections:
  required: 
  - k8s_auth
  properties:
    k8s_auth:
      $ref: massdriver/kubernetes-cluster

ui:
  ui:order:
  - port
  - log_level

app:
  envs:
    LOG_LEVEL: .params.log_level
    PORT: .params.port
  policies: []
    - .connections.k8s_auth.data.security.iam.subscribe

```
