### ISSUE TITLE
Add .github/workflow for publishing

### ISSUE THREAD

**Issue by coryodaniel** [massdriver-cloud/massdriver-cli#12]
Add a github workflow to terraform generator for publishing a bundle on merge.

We can base this on the one in massdriver-bundles. Should we make an actual action or just combine these two steps?

We should make massdriver-cli make actual build releases instead of tars so we don't have to do `make`

```yaml
name: Publish bundle to Massdriver

on:
  push:
    branches:
      - main

jobs:
  publish_to_massdriver:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download massdriver cli
        uses: dsaltares/fetch-gh-release-asset@0.0.8
        with:
          repo: "massdriver-cloud/massdriver-cli"
          file: "^mass-.*-linux-amd64\\.tar\\.gz$"
          regex: true

      - name: Publish
        env:
          MASSDRIVER_API_KEY: ${{ secrets.MASSDRIVER_API_KEY }}
        run: tar -xzf mass-*.tar.gz && ./mass bundle publish
```
